# Generated by Django 6.1 on 2026-09-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('host', 'Host'), ('web_app', 'Web Application'), ('repo', 'Code Repository'), ('api', 'API Endpoint'), ('cloud_resource', 'Cloud Resource')], max_length=32)),
                ('identifier', models.CharField(help_text='Unique handle, e.g. hostname, repo URL, or ARN', max_length=255, unique=True)),
                ('criticality', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=16)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('new', 'New'), ('validating', 'Validating'), ('validated', 'Validated - Exploitable'), ('false_positive', 'False Positive'), ('fixed', 'Fixed')], default='new', max_length=16)),
                ('sources', models.CharField(default='', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='findings.asset')),
            ],
            options={
                'ordering': ['-cvss_score'],
            },
        ),
    ]
